name: Build Docker containter and push to DO registry

on:
  workflow_call:
  workflow_dispatch:

  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  test_django_job:
    uses: mehedikhan72/Django-Kubernetes/.github/workflows/test-django.yaml@master
  docker_build:
    runs-on: ubuntu-latest
    needs: [test_django_job] 
    env:
      DJANGO_SECRET_KEY: "for-later"
    steps:
    - uses: actions/checkout@v3
